server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
management:
  endpoint.shutdown.enabled: true
  endpoints.web.exposure.include: '*'
  endpoint.info.enabled: true


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  logstash:
    enabled: true
    url: ${logstash.url}