server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint.shutdown.enabled: true
  endpoints.web.exposure.include: '*'
  endpoint.info.enabled: true
  

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  logstash:
    enabled: true
    url: ${logstash.url}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: people-service
        uri: lb://people-service
        predicates:
        - Path=/people/**
        filters:
        - RewritePath=/people/(?<path>.*), /$\{path}
      - id: portfolio-service
        uri: lb://portfolio-service

        predicates:
        - Path=/portfolio/**
        filters:
        - RewritePath=/portfolio/(?<path>.*), /$\{path}
      - id: auth-service
        uri: lb://auth-service
        predicates:
        - Path=/auth/**
        filters:
        - RewritePath=/auth/(?<path>.*), /$\{path}