server:
  port: 8062

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  logstash:
    enabled: true
    url: ${logstash.url}

management:
  endpoint.shutdown.enabled: true
  endpoints.web.exposure.include: '*'
  endpoint.info.enabled: true
                
zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: auth-service
    people:
      path: /people/**
      serviceId: people-service
    portfolio:
      path: /portfolio/**
      serviceId: portfolio-service